[main]
Title=Add Custom Batch and run at Start-up
Description=
Selected=False
Level=5
Author=Misty
Version=20220618
Date=2022-06-18

[Interface]
pTextLabel1="Add #$qMiniWinFE.custom.cmd#$q to the build. This script will be executed by winpeshl during the boot process.",1,1,8,45,487,52,10,Bold
pButton10="Edit MiniWinFE.custom.cmd",1,8,6,107,148,25,Edit,0,True,_Edit_,True

[Edit]
ShellExecuteEx,Open,notepad.exe,#$q%Programs%\custom.cmd\MiniWinFE.custom.cmd#$q

[process]
Run,%ScriptFile%,CHECKS
Run,%ScriptFile%,COMMON

[CHECKS]
If,Not,ExistFile,"%Programs%\custom.cmd\MiniWinFE.custom.cmd",Begin
Message,Custom .cmd is missing - exiting script...,Error,5
Exit,Custom .cmd  is missing - exiting script...,WARN
End

[COMMON]
FileCopy,"%Programs%\custom.cmd\MiniWinFE.custom.cmd",%Target_System32%
//Wait,1

[AuthorEncoded]
Logo=settings.ico
settings.ico=653,871

[EncodedFile-AuthorEncoded-settings.ico]
lines=0
0=eJztlzFLI0EYht9gEawCFnJdplAQLfQHBEW4H3KttaWosfIHWIr9tXbhuCLhOMLdXwjIcvcDXEE0Rcj6ffPNormN3sxmJ7ML+4Q3LyyZ7DMLuzsDNOiztwf6Vvi6CawD2KLQIXyBHNdsoKbGhjZlSHmkXAZ2cUVRIkryJlcBfVxQyLpXZQ4K77uXfQ4K/3cv6xwU7N3TlOWeVnB35zwuXzWDQj53znDptrMo5Hfnce0l+75FYTF3tVzdGRRq9xAo1O4hUKjdQ6BQuxfNDuWE0qPcUR4oMWVEuaUcUzoldN+nDHI6hXRfpVx79vblvkb5VVF3vu6/K+rO3FTY/bDC7szPCrvvenbndDy5MxcW55+a5PU/9uj/3cL9yCTvHG49+v+1cE/JO4eRR/9nS/dF5hB79H9ycE9xncODJ3fmD9zcU1zmcFe49Svf4O6eYjuHXoG+/3KKfO6Avf9JUbJz2IZf98ScwyefHX/v4j4oTrMQXJ89+2E05+Lqfh1Gcy6u7ryPWw1imsXVnfdxa0FMs7i68z6uLNedn0u27rwHOgyj+SH87OZ3HL+nea3B6yVe8/G6ldfevH/YDWZXE4REM9vjc+n4QDpqS/db0t2mNFZ0T01PTI9Nx5DfRZBxfcj/dCH/C+jzTPVdw8Mbumm4bhrO3QdaidxYbfqaUB9Qj6nPE9lQJNIN7gg0XLrJrYfP60+mO6bPTCfSg6Sr+4fpoTl+PyUN9pmYHpMOd2w6Ii3xluvZXZHutzLXmfsFmCR9knic4ylOLSnJzEsv1stMzmcYBSMN7FOF0I5M2OUtLh+2Y2ACAJzcCBstMDmuAQAAAAIAAAAoAAAAQQIAAAAAAAABAAAAAAAAAAAAAAA

